---
# tasks file for mysql-master
- name: Install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
    - mysql-server
    - mysql
    - mysql++-devel.x86_64
    - MySQL-python

- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0755

- name: Create MariaDB PID directory
  file: path=/var/run/mysqld state=directory owner=mysql group=mysql mode=0755

- name: Creat my.cnf.d directory 
  file: path=/etc/my.cnf.d state=directory mode=0755

# 配置文件 
- name: Create mysql configure file
  template: src=server.cnf.j2 dest=/etc/my.cnf.d/server.cnf

# 将 server.conf 添加到主配置
- name: /etc/my.cnf include  /etc/my.cnf.d/
  lineinfile:
    dest=/etc/my.cnf
    line='!includedir /etc/my.cnf.d'
  notify:
    - restart mariadb

#- name: Start mariadb
#  service: name=mariadb state=started enabled=yes
#  when: ansible_distribution_major_version == "7"

- name: Start mariadb
  service: name=mysqld state=started enabled=yes
  when: ansible_distribution_major_version == "6"

- name: Get the current master servers replication status 
  mysql_replication: 
    mode=getmaster 
  delegate_to: "{{ mysql_master }}"
  register: repl_stat 

- name: Change the master in slave to start the replication 
  mysql_replication: 
    mode=changemaster
    master_host={{ mysql_master }}
    master_log_file={{ repl_stat.File }} 
    master_log_pos={{ repl_stat.Position }} 
    master_user={{ mysql_repl_user[0].name }} 
    master_password={{ mysql_repl_user[0].pass }} 

- name: start slave in slave to start the replication 
  mysql_replication: 
    mode=startslave 

